### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by cyberpunkbln** [MrDimkasStudio/MachinePowerCraft-api#5]
Hello,

i have Machine Power Craft 2 included, minecraft stops loading  and i will receive following Crash-Report:
This is the only part whats different betwen the other logs.

```
java.lang.ArrayIndexOutOfBoundsException


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:356)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:356)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

```

Thx i want to try the Quarry:).

**Comment by MrDimkasStudio** [comment]
Can you leave the FULL crash-report, because I can tell that it is a small piece of it. And until then: PLEASE don't report crashes of this size to ANY developer.
